language: scala
scala:
  - 2.10.5

jdk:
  - oraclejdk8

branches:
  only:
    - master

script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt 'release with-defaults'; else sbt validate; fi"
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

notifications:
  email:
    recipients:
      - timothy.m.perrett@one.verizon.com
      - andrew.mohrland@one.verizon.com
      - cody.allen@one.verizon.com
    on_success: change
    on_failure: always
